import { pgTable, serial, text, varchar, timestamp, boolean, integer, decimal } from "drizzle-orm/pg-core";

export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  firstName: varchar("first_name", { length: 100 }).notNull(),
  lastName: varchar("last_name", { length: 100 }).notNull(),
  email: varchar("email", { length: 150 }).notNull().unique(),
  password: text("password").notNull(),
  address: varchar("address", { length: 255 }),
  phone: varchar("phone", { length: 30 }),
  profileImage: varchar("profile_image", { length: 255 }),
  backgroundImage: varchar("background_image", { length: 255 }),
  role: varchar("role", { length: 50 }),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const crops = pgTable("crops", {
  id: serial("id").primaryKey(),
  name: varchar("name", { length: 255 }).notNull(),
  cropType: varchar("crop_type", { length: 255 }),
  variety: varchar("variety", { length: 255 }),
  startMethod: varchar("start_method", { length: 255 }),
  germinationRate: decimal("germination_rate", { precision: 5, scale: 2 }),
  seedPerCell: integer("seed_per_cell"),
  lightProfile: varchar("light_profile", { length: 255 }),
  soilCondition: varchar("soil_condition", { length: 255 }),
  daysToEmerge: integer("days_to_emerge"),
  plantSpacing: decimal("plant_spacing", { precision: 10, scale: 2 }),
  rowSpacing: decimal("row_spacing", { precision: 10, scale: 2 }),
  plantingDepth: decimal("planting_depth", { precision: 10, scale: 2 }),
  averageHeight: decimal("average_height", { precision: 10, scale: 2 }),
  daysToFlower: integer("days_to_flower"),
  daysToMaturity: integer("days_to_maturity"),
  harvestWindow: integer("harvest_window"),
  lossRate: decimal("loss_rate", { precision: 5, scale: 2 }),
  harvestUnit: varchar("harvest_unit", { length: 50 }),
  estimatedRevenue: decimal("estimated_revenue", { precision: 15, scale: 2 }),
  expectedYield: decimal("expected_yield", { precision: 15, scale: 2 }),
  plantingDetails: text("planting_details"),
  pruningDetails: text("pruning_details"),
  botanicalName: varchar("botanical_name", { length: 255 }),
  isPerennial: boolean("is_perennial").default(false),
  autoCreateTasks: boolean("auto_create_tasks").default(true),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
  createdBy: integer("created_by").references(() => users.id),
  updatedBy: integer("updated_by").references(() => users.id),
});

export const mediaLocations = pgTable("media_locations", {
  id: serial("id").primaryKey(),
  name: varchar("name", { length: 255 }).notNull(),
  internalId: varchar("internal_id", { length: 255 }),
  electronicId: varchar("electronic_id", { length: 255 }),
  locationType: varchar("location_type", { length: 255 }),
  plantingFormat: varchar("planting_format", { length: 255 }),
  numberOfBeds: integer("number_of_beds"),
  bedLength: decimal("bed_length", { precision: 10, scale: 2 }),
  bedWidth: decimal("bed_width", { precision: 10, scale: 2 }),
  area: decimal("area", { precision: 15, scale: 4 }),
  estimatedLandValue: decimal("estimated_land_value", { precision: 15, scale: 2 }),
  status: varchar("status", { length: 255 }),
  lightProfile: varchar("light_profile", { length: 255 }),
  grazingRestDays: integer("grazing_rest_days"),
  description: text("description"),
  geometry: text("geometry"), // Assuming geometry is stored as text/JSON for now
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
  createdBy: integer("created_by").references(() => users.id),
  updatedBy: integer("updated_by").references(() => users.id),
});

export const plantings = pgTable("plantings", {
  id: serial("id").primaryKey(),
  cropId: integer("crop_id").references(() => crops.id),
  locationId: integer("location_id").references(() => mediaLocations.id),
  plantingQuantity: decimal("planting_quantity", { precision: 10, scale: 2 }),
  plantingMethod: varchar("planting_method", { length: 255 }),
  plantingDate: timestamp("planting_date"),
  seedingDate: timestamp("seeding_date"),
  plantSpacing: decimal("plant_spacing", { precision: 10, scale: 2 }),
  rowSpacing: decimal("row_spacing", { precision: 10, scale: 2 }),
  rowLength: decimal("row_length", { precision: 10, scale: 2 }),
  numberOfRows: integer("number_of_rows"),
  electronicId: varchar("electronic_id", { length: 255 }),
  currentlyPlanted: boolean("currently_planted").default(false),
  harvestPlan: text("harvest_plan"),
  estimatedYield: decimal("estimated_yield", { precision: 15, scale: 2 }),
  estimatedProfit: decimal("estimated_profit", { precision: 15, scale: 2 }),
  plantingInfo: text("planting_info"),
  status: varchar("status", { length: 50 }).default('active'),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
  createdBy: integer("created_by").references(() => users.id),
  updatedBy: integer("updated_by").references(() => users.id),
});
